### ISSUE TITLE
Exception at --> automator.GetInfo(); 

### ISSUE THREAD

**Issue by Tailor321** [ihtfw/TeamViewer.QuickSupport.Integration#1]
Hello, 
i get an exception in your example at this Point -->   var info = automator.GetInfo(); 
(But only if i use the quicksupport Version)
Error message: NonComVisibleBaseClass
The Error is in Automator.cs 
![2018-02-28exception helperwindow](https://user-images.githubusercontent.com/36927226/36797378-aff1428a-1c9f-11e8-8f2f-8b54350c7a1a.png)

Do you have the same problem ?

**Comment by ihtfw** [comment]
Hello.

I would investigate this problem. Could you tell me QuickSupport version that you are using?

**Comment by ihtfw** [comment]
I've tested with latest QuickSupport(https://download.teamviewer.com/download/TeamViewerQS.exe) and it works. Run from with configuration Debug AnyCPU on Windows 10 x64

**Comment by Tailor321** [comment]
I use the latest QuickSupport version too. (And the same configuration: Windows 10 x64, AnyCPU, Visual Studio 2015)
Here my current pozess:
1. I uninstalled all versions of Teamviewer
2. I have create an test Project (simple Windows Form Appllication) and installed your program from nuget. 
3. I copy your sample code into the form_load() method and comment the line "UpdateQuickSupportInBackground(quickSupportDownloader);" out, because I had no update funktions.
4. --> run the project 
Here you can download the test project:   https://we.tl/ux7j0SQAdW

Thanks for your help !

**Comment by ihtfw** [comment]
Tested your project and it works fine with full version TeamViewer and QuickSupport version
![image](https://user-images.githubusercontent.com/680417/36856633-0e8c4056-1da9-11e8-8e7e-a4c3cbba841c.png)
Did you tried to run without attached debugger? May be you disabled "Enable Just My Code" option? In general it should be checked.
![image](https://user-images.githubusercontent.com/680417/36856783-6c78d4d6-1da9-11e8-9cf2-21b7151eed3b.png)

**Comment by Tailor321** [comment]
Hello, 
sry for my late reply, 
--> I testet this option, but the problem still exist.  
But I found an other option:
If I start the test project, the user account control shows a message --> if i say no it works. But if I say yes it doesn`t work. --> this is very strange. I'm logged in as a normal lokal windows administrator 
![user account control](https://user-images.githubusercontent.com/36927226/37236319-a65fe3ac-2406-11e8-818a-d27264e11c3d.jpg)
--> i testet this project at 3 other pc's, but all have the same problem. 
Would you have an idea how this message no longer seems and it still works?

**Comment by ihtfw** [comment]
You could turn off UAC on machine. 
![image](https://user-images.githubusercontent.com/680417/37319142-778e3230-26a0-11e8-92e8-f097541e4597.png)

**Comment by Tailor321** [comment]
hm sry, 
if i do this, it doesn't work. the same error message.....

**Comment by Mystogun** [comment]
I had the same problem too, you can solve it by adding a manifest file and setting the `requestedExecutionLevel` to `requireAdministrator`

`<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />`

and it should work just fine

**Comment by ihtfw** [comment]
Thanks Mystogun!

I've also faced with this problem. It's because of elevated rights of teamviewer on machine. It's impossible to access textbox in teamviewer from another app with user rights if teamviewer is run as admin.

So there are two solutions:
1. Run your app as admin
2. Run TeamViewer as User(sometimes it's impossible, then use first approach)
