### ISSUE TITLE
Missing UpdateQuickSupportInBackground(quickSupportDownloader)

### ISSUE THREAD

**Issue by ProgramerAnel** [ihtfw/TeamViewer.QuickSupport.Integration#2]
Have a problem with missing function/procedure. 

![image](https://user-images.githubusercontent.com/24620814/43628089-36a1f3e6-96f9-11e8-9e08-4ff0ca70f1a7.png)

Is it up to me ?

**Comment by ihtfw** [comment]
Sorry for that. Missed this function for example.
```csharp
private static void UpdateQuickSupportInBackground(QuickSupportDownloader quickSupportDownloader)
{
    Task.Factory.StartNew(() =>
     {
         try
         {
             quickSupportDownloader.Update();
         }
         catch (Exception updateEx)
         {
             Debug.WriteLine("Failed to update QuickSupport: " + updateEx);
         }
     });
}
```

Will add it to readme. Thanks for report!

**Comment by ProgramerAnel** [comment]
It works now, thanks.

Also i have one more problem

Using custom QS version : 6.0.17222 QSC
And your nudget package

![image](https://user-images.githubusercontent.com/24620814/43630827-bacd5996-9701-11e8-9251-706e6449110b.png)

**Comment by ihtfw** [comment]
Something is different in your version. Could you send it to me? I'll try to fix bug

**Comment by ProgramerAnel** [comment]
Thanks for your fast reply. 

Sure here is link : [https://drive.google.com/open?id=1i33r3hzyW5Nh7I-Rm6pqZeD284VqEu5t](url)

**Comment by ihtfw** [comment]
I'll try to check it today or on weekend.

**Comment by ihtfw** [comment]
Checked your project. It not working because QS is running as admin and your up as user. If you run it as admin too, then everything works
![image](https://user-images.githubusercontent.com/680417/43643023-f1f27512-9753-11e8-97d4-1406c8680753.png)
